### ISSUE TITLE
your module doesn[t display in my MMM

### ISSUE THREAD

**Issue by treile** [kyle-kelly/MMM-uber#1]
i do everything like you put in the README, and everything is fine, no error, but it doesnt appear in my MMM, i try all the possible bug but nothing works. please heeeeeeeeeeeeeeeelp
this are my config 
`	modules: [
		{
			module: "alert",
		},

{
	module: 'MMM-uber',
	position: 'top_left',
	header: 'Uber (DC)',
	config: {
		lat: -36.7912327,  // use your exact pickup loaction
		lng: -73.0553248, // use your exact pickup loaction
		uberServerToken: '<3owC9SRoaxJyqTd3i_BH76gMKLRWgYzK9mYSsAxx>',
	} },
		{
			module: "updatenotification",
			position: "top_bar"`

**Comment by kyle-kelly** [comment]
Try removing the `<` and `>` characters from your Uber server token. If that doesn't work please post your log. 

Also, as a matter of good security practice, don't post your Uber server token.

**Comment by treile** [comment]
It didnt work. What do you mean by log??  (am a noob}. i dont have any errors, it just doesnt display on the MM when i ask for a ride. Any idea?

**Comment by kyle-kelly** [comment]
I am not convinced that this is a bug. I am going to close this issue. Please take a look [here](https://forum.magicmirror.builders/topic/4295/mmm-uber-and-mmm-lyft/) and seek help from that forum.
