### ISSUE TITLE
Title in other module

### ISSUE THREAD

**Issue by CraigDamlo** [kyle-kelly/MMM-uber#3]
The title overlaps into the module above it, if it's not the top module.

**Comment by kyle-kelly** [comment]
Yea I don't know CSS and haven't bothered to learn. I'll try to resolve if you can post a screen shot of the problem.

**Comment by CraigDamlo** [comment]
![img-4252](https://user-images.githubusercontent.com/6207622/38205662-3683b99c-365c-11e8-807a-9037386fcd88.JPG)
It's a little hard to see, but if you can kind of see TIMES over map error.

**Comment by kyle-kelly** [comment]
I see. I'll try a fix later this week or weekend. In the meantime don't be afraid to fool around with it and post a solution here.

**Comment by CraigDamlo** [comment]
I've fixed the css and submitted a pull request.

**Comment by kyle-kelly** [comment]
Well, I'm finally getting around to this. I've found that your proposed fix actually creates a bottom interference on my mirror. I believe the CSS format is very subject depending on the orientation of the mirror and the layout / number of modules.

Thanks for downloading and helping out. I'm going to close this as it's not really a code issue.
