### ISSUE TITLE
Checking Uber status

### ISSUE THREAD

**Issue by SoftwareEngineerInTraining** [kyle-kelly/MMM-uber#7]
It never shows the uber times. Just stuck on "Checking uber status..."

**Comment by kyle-kelly** [comment]
Run the mirror from your browser and read the output from the console. Intuition says that you've entered the incorrect key in your config.

**Comment by SoftwareEngineerInTraining** [comment]
I’m sorry but how do you run the mirror from my browsers and read the output. Pretty new here

**Comment by kyle-kelly** [comment]
Ask for help here: https://forum.magicmirror.builders/

This isn't the appropriate place for general questions. Please reserve this space for actual bug reports.
