### ISSUE TITLE
Errors in example configuration

### ISSUE THREAD

**Issue by anthony6608** [kyle-kelly/MMM-uber#8]
This may seem insignificant and small but to prevent any new users from wasting time trying to figure out what's wrong, I figured I would open an issue for you to correct this to make things easier for everyone. Both the uber and Lyft modules are the same issue.

I copied/pasted the example configuration only for my MagicMirror to crash and complain about the config file:

Example configuration (changes are in bold):

{
    module: 'MMM-lyft',
    position: **'top_left',** // (the  ' is not a ' and is causing the configuration to complain)
    header: 'Lyft (DC)',
    config: {
        **lat: XX.XXXX,  // this should be in ' '
        lng: XX.XXXX, // this should be in ' ' as well.**
        clientId: '<your client ID>', 
        clientSecret: '<your client secret>',
    }
},

Thanks :D

**Comment by kyle-kelly** [comment]
This is incorrect. The two characters in the position line have the same ASCII value so I don't know what you're referring to. Additionally, the lat an lng values do not need to be in single quotes.

I am not sure what your issue was, but it was misdiagnosed.
