### ISSUE TITLE
How to change font and have both modules directly underneath each other?

### ISSUE THREAD

**Issue by anthony6608** [kyle-kelly/MMM-uber#9]
Hi,

First off thank you very much for this cool module! It will definitely be useful to me. 

I was wondering, what is the easiest/safest way to change the font on both the uber/lyft modules? Also, when I place them both on the right side of my mirror, there is big gap between the two (also I have no header for both of them) ... how can I get rid of the gap and have them line up perfectly underneath each other with no spacing? Thank you!

**Comment by kyle-kelly** [comment]
I am happy you are enjoying the module and I that I was able to contribute in a meaningful way.

This is not an issue. To modify the general shape of the module, please look at the `.css` file. If you feel you have created a better format, please issue a pull request.

Please see [here](https://forum.magicmirror.builders/category/8/custom-css) for help with CSS formatting.
